hmcts/rd-commondata-dataload

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-3636
Changes made to sync master build with demo,ithc and perftest
```
[ ] Yes
[ x] No
```
> RDCC-3636:Changes made to sync master build with demo,ithc and perftest

- src/main/resources/db/migration/V1_5__insert_additional_facilities.sql
- src/main/resources/db/migration/V1_6__update_view_mv_list_of_values.sql
> Create and Insert Additional Facilities table

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-4048
Fixed CVEs
```
[ ] Yes
[x] No
```
> RDCC-4048: Fix CVEs

- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/IFlagCodeProcessor.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagServiceTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/listener/JobResultListenerTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagServiceMapperTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessorTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataFlagServiceRouteTaskTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataExecutorTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadUtilsTest.java
https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[X] No
```
> fixed sonar issues

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Gradle Upgrade 7.3.3
```
[ ] Yes
[x] No
```
> Gradle Upgrade 7.3.3

- build.gradle
CVE Fix for Jackson Bind
```
[ ] Yes
[X] No
```
> CVE Fix for Jackson

- build.gradle
CVE Fix
```
[ ] Yes
[ X] No
```
> CVE Fix for postgresql

- src/main/resources/application-crd-list-of-values-router.yaml
- src/main/resources/db/migration/V1_6__Alter_List_Of_Values.sql
https://tools.hmcts.net/jira/browse/RDCC-4412
Change a single unique key in to a composite key
```
[ ] Yes
[X] No
```
> change unique key in to composite

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4504
cve 2022-22968
```
[ ] Yes
[X] No
```
> commondata-dataload-Nightly build failure 

- Dockerfile
- build.gradle
- docker-compose.yml
https://tools.hmcts.net/jira/browse/RDCC-4352
Java 17 Migration for Common Reference Data
```
[ ] Yes
[x ] No
```
> Feat:Java 17 Migration for Common Reference Data

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4707
```
[ ] Yes
[X] No
```
> Bumped spring dependencies version to 5.3.20

- build.gradle
> Nightly build failed due to mutation test coverage for new class

- src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
https://tools.hmcts.net/jira/browse/RDCC-4754
```
[ ] Yes
[X] No
```
> Commondata:correct the date format in flag details table of common reference data

- Dockerfile
- acb.tpl.yaml
> Common data Add multi arch image configuration

- build.gradle
- charts/rd-commondata-dataload/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4696
Updated library version to latest
```
[ ] Yes
[x] No
```
> Update data ingestion library version to latest - CVE Fix

- renovate.json
https://tools.hmcts.net/jira/browse/RDCC-4823
Configured renovate
```
[ ] Yes
[x] No
```
> config: RDCC-4823 Configured renovate

- .github/workflows/combine-prs.yml
> commmon data Load Auto merge renovate PRs

- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataFunctionalBaseTest.java
- src/functionalTest/resources/application-functional.yml
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCategoriesRouteTask.java
> Rdcc 4991fix

- charts/rd-commondata-dataload/Chart.yaml
- charts/rd-commondata-dataload/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDCC-5065
upgraded bitnami chart version
```
[ ] Yes
[x] No
```
> RDCC-5065: upgraded bitnami chart version

- build.gradle
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
https://tools.hmcts.net/jira/browse/RDCC-5234
Require Changes on Processor logic added for duplicate comp key records in Audit table
```
[ ] Yes
[X] No
```
> fix for handling 'D' records

- build.gradle
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCategoriesRouteTask.java
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadConstants.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCategoriesRouteTaskTest.java
Active D Flag Deletions
```
[ ] Yes
[X] No
```
> Active D Flag Deletion

- config/owasp/suppressions.xml
> RDCC-5392: adding suppression for CVE-2022-25857

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-5853
enabling Fortify Scan
```
[ ] Yes
[x] No
```
> RDCC-5853: enabling Fortify Scan

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-5853
Fix - Syncing Fortify Config with PRD
```
[ ] Yes
[x] No
```
> RDCC-5853: Fix - Syncing Fortify Config with PRD

- src/functionalTest/resources/dbmigration/V1_11__alter_flag_service_details.sql
- src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Reverts hmcts/rd-commondata-dataload#185
> Revert "Case Flags : Add two new columns in Flag Service table : RDCC 5571"

- src/functionalTest/resources/dbmigration/V1_11__alter_flag_service_details.sql
- src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Reverts hmcts/rd-commondata-dataload#189
> Revert "Revert "Case Flags : Add two new columns in Flag Service table : RDCC 5571""

- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
- src/functionalTest/resources/application-functional.yml
- src/functionalTest/resources/sourceFiles/flagService/flag_service_failure.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_failure_foreignkey_violation.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_partial_hearingrelevant_string.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_partial_success.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_partial_success_id_notnumeric.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_success.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_success_day2.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_success_default_values_for_default_status_available_externally.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_success_insensitive_headers.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_success_leadingspace.csv
- src/functionalTest/resources/sourceFiles/flagService/flag_service_success_with_quotes.csv
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagService.java
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagServiceMapper.java
- src/main/resources/application-crd-flag-service-router.yaml
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagServiceTest.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagServiceMapperTest.java
https://tools.hmcts.net/jira/browse/RDCC-5600
Case Flags : ETL ingestion for Flag Service
```
[ ] Yes
[x] No
```
> Rdcc 5600 case flags etl ingestion for flag service

- src/functionalTest/resources/dbmigration/V1_13__Insert_table_flag_details.sql
- src/main/resources/db/migration/V1_13__Insert_table_flag_details.sql
https://tools.hmcts.net/jira/browse/RDCC-5914
Case Flags : Refresh Flag Details with new file
```
[ ] Yes
[X] No
```
> RDCC-5914 -Refresh Flag Details

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCaseLinkingLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataBlobSupport.java
- src/functionalTest/resources/application-functional.yml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-6046
RDCC-6046 [Spring Boot upgrade - Dataload project] fix for CommonDataLoad project
```
[ ] Yes
[ x] No
```
> RDCC-6046 [Spring Boot upgrade - Dataload project]

- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
- src/functionalTest/resources/application-functional.yml
- src/main/resources/application-crd-list-of-values-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-6155
changing `header-validation-enabled` flag to `false`
```
[ ] Yes
[x] No
```
> RDCC-6155: changing `header-validation-enabled` flag to `false`

- build.gradle
- charts/rd-commondata-dataload/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6244
[RDCC-6244]-Upgrade OWASP security libs in data ingestion
```
[ ] Yes
[ x] No
```
> [RDCC-6244]-Upgrade OWASP security libs in data ingestion

- src/main/resources/application-crd-flag-details-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-6300
```
[ ] Yes
[X] No
```
> header disable

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
- src/functionalTest/resources/sourceFiles/categories/list_of_values_utf8_header.csv
- src/main/resources/application-crd-list-of-values-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-6450
Add header validation to check UTF-8 file format
```
[ ] Yes
[ x] No
```
> Feat:Common : Add header validation to check UTF-8 file format

- src/main/resources/application-crd-flag-details-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-6450
[RDCC-6450]-changed the validation flag as true
```
[ ] Yes
[x ] No
```
> [RDCC-6450]-changed the validation flag as true

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6428
Address CVEs in all Reference Data repositories - Common Reference Data
```
[ ] Yes
[x ] No
```
> Feat:Address CVEs in all Reference Data repositories - Common Reference Data

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-6242
[RDCC-6242]-Upgrade Libs in Data load projects
```
[ ] Yes
[ x] No
```
> [RDCC-6242]-Upgrade Libs in Data load projects

- Jenkinsfile_CNP
- build.gradle
- charts/rd-commondata-dataload/Chart.yaml
- charts/rd-commondata-dataload/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DTSRD-148
Helm chart update for blob storage
```
[ ] Yes
[x] No
```
> Addresses PR pipeline failure

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-72
Uplifting spring-boot to latest 2.7.x before upgrade to 3.0 following:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
```
[ ] Yes
[x] No
```
> Update to spring-boot 2.7.10

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-72
Preparation for spring-boot 3.x upgrade
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
https://docs.spring.io/spring-security/reference/5.8/migration/index.html
```
[ ] Yes
[x] No
```
> Update spring-security to 5.8.2

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-327
Applied remedy from https://spring.io/security/cve-2021-22044
```
[ ] Yes
[x] No
```
> Addresses CVE-2021-22044

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-47
Removed suppressions for remedied CVEs
```
[ ] Yes
[x] No
```
> removed suppressions

- build.gradle
- config/owasp/suppressions.xml
> Suppress CVE's CVE-2023-34035, CVE-2023-34034

- build.gradle
- charts/rd-commondata-dataload/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSRD-1175
upgraded spring cloud library version 
```
[ ] Yes
[ *] No
```
> DTSRD-1175

- .github/renovate.json
- build.gradle
- renovate.json
- Updating renovate config.
https://tools.hmcts.net/jira/browse/DTSRD-1219
```
[ ] Yes
[x] No
```
> DTSRD-1217

- config/owasp/suppressions.xml
> CVE-2023-34047

- src/main/resources/application.yaml
> Update application.yamlto add schema to connection string

- src/main/resources/application.yaml
> Update application.yaml. Reverting changes to connection string

- config/owasp/suppressions.xml
Suppresses CVE-2023-36052 (likely a false positive)
```
[ ] Yes
[x] No
```
> Suppresses CVE-2023-36052 

- build.gradle
Remedies CVE-2023-35887
```
[ ] Yes
[x] No
```
> Addresses CVE-2023-35887

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Update dependencycheck to use default

- build.gradle
- config/owasp/suppressions.xml
> Fix CVE CVE-2023-48795

- charts/rd-commondata-dataload/Chart.yaml
> Update chart job version

- src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
- src/functionalTest/resources/sourceFiles/categories/list_of_values_delete_success.csv
- src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
- src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
https://tools.hmcts.net/jira/browse/DTSRD-2516
```
[ ] Yes
[ *] No
```
> DTSRD-2516.Updating code to enable deleting of records

- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/DTSRD-2766
Updated gradle, plugins and suppressions cleanup
```
[ ] Yes
[x] No
```
> DTSRD-2766

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-3025
```
[ ] Yes
[ ] No
```
> Removed deprecated dependency

- build.gradle
> Build fix - restore junit 5.9.2 and junit-platform 1.9.2

- build.gradle
> disable pitest verbose logging

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-3685
CVE-2024-38820 Suppression
```
[ ] Yes
[x] No
```
> DTSRD-3685 CVE-2024-38820 Suppression

- build.gradle
Enables verbose logging for pitest
```
[ ] Yes
[x] No
```
> Diagnosing nightly build failure

- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/CME-300
```
[ ] Yes
[x ] No
```
> CME-300: Update azurerm

- build.gradle
https://tools.hmcts.net/jira/browse/CME-13
Add plugins missing from https://github.com/hmcts/rd-commondata-dataload/pull/414
```
[ ] Yes
[x ] No
```
> DTSRD-72: Fix nightly build

- build.gradle
Update HMCTS gradle plugin to 0.12.64
```
[ ] Yes
[x] No
```
> Update HMCTS gradle plugin to 0.12.64

- src/main/resources/db/migration/V1_9__recreate_spring_batch_tables.sql
> Recreating spring batch tables

- src/main/resources/db/migration/V1_9__recreate_spring_batch_tables.sql
> Recreate batch tables

- charts/rd-commondata-dataload/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSRD-4522
changed repo from bitnami to hmctspublic
```
[ ] Yes
[x] No
```
> DTSRD-4522

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-4788
Update data-ingestion-lib to 0.6.0.4_beta
```
[ ] Yes
[x] No
```
> DTSRD-4788

- build.gradle
Removes arcmutate-spring
```
[ ] Yes
[x] No
```
> Nightly build fix
